[package]
name = "ganhash"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0.9", features = ["abigen", "ws", "rustls"] }
jsonrpsee = { version = "0.20.3", features = ["full"] }
serde_json = "1.0.108"
tokio = { version = "1.32.0", features = ["full"] }
