version: '3.3'
services:
  node-erigon:
    image: ghcr.io/topos-protocol/erigon:${JERIGON_VERSION}
    container_name: node-erigon
    init: true
    command:
      - '--datadir=/home/erigon/.local/share/erigon'
      - '--chain=dev'
      - '--private.api.addr=0.0.0.0:9090'
      - '--mine'
      - '--http.api=eth,erigon,web3,net,debug,trace,txpool,parity,admin'
      - "--http.corsdomain='*'"
      - '--http.addr=0.0.0.0'
      - '--http.port=$ERIGON_RPC_PORT'
      - '--p2p.allowed-ports=30303'
      - '--p2p.protocol=67'
    ports:
      - $ERIGON_RPC_PORT:$ERIGON_RPC_PORT
      - '30303'
    volumes:
      - erigon-data:/home/erigon/.local/share/
      - ./assets/nodekey:/home/erigon/.local/share/erigon/nodekey
    environment:
      - ERIGON_RPC_PORT=${ERIGON_RPC_PORT}

  node-jerigon:
    image: ghcr.io/topos-protocol/erigon:${JERIGON_VERSION}
    entrypoint: ['/bin/sh']
    container_name: node-jerigon
    init: true
    user: root
    command:
      - '/home/erigon/.local/share/run-stateless.sh'
    depends_on:
      node-erigon:
        condition: service_started
    ports:
      - $JERIGON_RPC_PORT:$JERIGON_RPC_PORT
      - '30304'
      - '30303'
    volumes:
      - erigon-data:/home/erigon/.local/share/
      - './assets/run-stateless.sh:/home/erigon/.local/share/run-stateless.sh'
    environment:
      - JERIGON_RPC_PORT=${JERIGON_RPC_PORT}
      - ERIGON_ENODE=${ERIGON_ENODE}
      - GENERATION_INTERVAL=${GENERATION_INTERVAL}

  # zero-bin:
  #   image: ghcr.io/topos-protocol/zero-bin:${ZERO_BIN_VERSION}
  #   container_name: zero-bin
  #   command:
  #     - '--runtime=in-memory'
  #     - 'http'
  #     - '--output-dir=/tmp/proofs'
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - RUST_LOG=debug
  #   volumes:
  #     - proof-data:/tmp/proofs

volumes:
  erigon-data:
  proof-data:
